name: flutter_app_tv
description: TvFlix

publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  carousel_slider: ^4.2.1
  webview_flutter: ^4.7.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  
  http: ^1.2.1
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  animated_text_kit: ^4.2.2
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.2.3
  firebase_core: ^2.31.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.5
  flutter_facebook_auth: ^6.2.0
  fluttertoast: ^8.2.5
  need_resume: ^1.0.7+1
  flutter_launcher_icons: ^0.13.1
  wakelock_plus: ^1.2.5
  flutter_math_fork: ^0.7.2
  provider: ^6.1.2
  transparent_image: ^2.0.1
  chewie: ^1.8.1
  video_player: ^2.8.6
  # pod_player: ^0.2.2

  cupertino_icons: ^1.0.0
  subtitle_wrapper_package: ^2.2.1
    # git:
    #   url: https://github.com/Ahtsham0715/flutter_subtitle_wrapper.git
    #   ref: main
  flutter_vlc_player: #^7.4.1
    path: flutter_vlc_player/flutter_vlc_player
    # git:
    #   url: https://github.com/Ahtsham0715/flutter_vlc_player/tree/master/flutter_vlc_player.git
    #   ref: master
  youtube_player_flutter: ^9.0.1
  device_info_plus: any
  # flick_video_player: ^0.8.0
  # visibility_detector: any
  # media_kit_video: any
  # media_kit: any
  # media_kit_libs_video: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  change_app_package_name: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:

 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
 
  fonts:
    - family: Oduda
      fonts:
        - asset: assets/fonts/Oduda.otf
  